project2:	project2.o	readline.o	bubblesort.o
			gcc	-o	project2	project2.o	readline.o	bubblesort.o

project2.o:	project2.c	readline.h
				gcc	-c	project2.c

readline.o:	readline.c	readline.h
			gcc	-c	readline.c

bubblesort.o:	bubblesort.c	bubblesort.h
			gcc	-c	bubblesort.c
