stackclient:		stackclient.o	stackADTH3.o
			gcc	-o	stackclient	stackclient.o	stackADTH3.o
stackclient.o:		stackclient.c	stackADTH.h
			gcc	-c	stackclient.c
stackADTH3.o:	stackADTH3.c	stackADTH.h
			gcc	-c	stackADTH3.c
